tool_tier: cyclic:gem_obsidian
tool_category: minecraft:pickaxe
break_speed: 16
attack_damage: 12.5
attack_speed: 1.2
can_sweep_attack: false
can_break_blocks_in_creative: true
max_durability: 6248
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "cyclic:gem_obsidian"
enchantment_value: 22
enchantment_categories: ["digger", "breakable"]