tool_tier: cyclic:emerald
tool_category: minecraft:sword
break_speed: 1.5
attack_damage: 8.5
attack_speed: 1.6
can_sweep_attack: true
can_break_blocks_in_creative: false
max_durability: 1593
item_damage_on_attack_entity: 1
item_damage_on_break_block: 2
repair_ingredient: "minecraft:emerald"
enchantment_value: 22
enchantment_categories: ["weapon", "breakable"]